### ISSUE TITLE
Use github fork badge?

### ISSUE THREAD

**Issue by danhyun** [rwinch/asciidoctor-gradle-examples#12]
What do you think about using a fork badge inplace of the link we have in the `gh-pages` index page.

I have a preview here http://danhyun.github.io/asciidoctor-gradle-examples/

![image](https://cloud.githubusercontent.com/assets/1033018/6444909/a00213c0-c0ce-11e4-8403-4716766e7690.png)

It's currently "fixed" but could set as "absolute" if you want.

**Comment by rwinch** [comment]
I think this is a great idea! If you send a PR, I'll merge it :)

**Comment by rwinch** [comment]
Closed via #13

**Comment by danhyun** [comment]
Thanks :)
